http_server:
  address: ":8080"
  timeout: 4s
  idle_timeout: 30s
postgres:
  postgres_db: "order"
  postgres_user: "order-user"
  postgres_password: "order-password"
  postgres_host: "localhost"
  postgres_port: "54321"
migration_dir: "file://migrations/"
migration_down: true
stan:
  cluster_id: "test-cluster"
  client_id: "client-id"
  dsn: "nats://localhost:4222"